version: '3.1'

services:
  data:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword

  backend:
    image: market
    restart: always
    ports:
      - 80:80
    depends_on:
      - data
    links:
      - data:database